### PR TITLE
Refactor Library to Support Other Formats

### PR DESCRIPTION
**Pull request by smizell**
Currently, halpert is set up to just support going from HTML+RDFa to HAL+JSON. I worked on extracting some of this functionality so that multiple formats can be supported. This is my proposed plan for it along with a feature branch with what I currently have. Any comments are appreciated.
## Data Structure

For each format that is supported, there are two functions needed: one for parsing the format and one for building the format. Currently, halpert only supports parsing HTML and building HAL+JSON. 

To do this parsing and building, I had to come up with a general object tree that the parses returned and the builders accepted. For what I have so far, I've come up with this:

``` javascript
{
  curies: [], // or namespaces? vocabularies?
  properties: {}
  links: {},
  embedded: {},
  queries: {},
  forms: {}
}
```

Each `embedded` resource MUST be an array of object literals that look like this: 

``` javascript
{
  properties: {}
  links: {},
  queries: {},
  forms: {}
}
```

So far, I have not implemented queries and forms in what I have for HTML and HAL, but I will. What the above structure allows for is a generalized format that can be derived from any type of object. Here is an example that is built from the HTML I have:

``` JSON
{
  "curies": [
    {
      "name": "ea",
      "href": "http://example.com/docs/rels/"
    }
  ],
  "properties": {
    "currentlyProcessing": "14",
    "shippedToday": "20"
  },
  "links": {
    "self": [{ "href": "/orders" }],
    "next": [{ "href": "/orders?page=2" }],
    "ea:admin": [
      {
        "href": "/admins/2",
        "title": "Fred"
      },
      {
        "href": "/admins/5",
        "title": "Kate"
      }
    ]
  },
  "embedded": {
    "ea:order": [
      {
        "properties": {
          "total": "30.00",
          "currency": "USD",
          "status": "shipped"
        },
        "links": {
          "self": [{ "href": "/orders/123" }],
          "ea:basket": [{ "href": "/baskets/98712" }],
          "ea:customer": [{ "href": "/customers/7809" }]
        }
      },
      {
        "properties": {
          "total": "20.00",
          "currency": "USD",
          "status": "processing"
        },
        "links": {
          "self": [{ "href": "/orders/124" }],
          "ea:basket": [{ "href": "/baskets/98713" }],
          "ea:customer": [{ "href": "/customers/12369" }]
        }
      }
    ]
  }
}
```
## API

I have also worked on changing up the API significantly. Now, it allows for this:

``` javascript
var halObj = Halpert.convert(html).from('html').to('hal_json');
```

the `.convert` function loads the initial data, `.from` parses it, and `.to` builds the HAL object. Although those are the only ones supported, it means that this could be done once Siren is supported:

``` javascript
var sirenObj = Halpert.convert(html).from('html').to('siren');
```

It also allows for not using a parser if you are doing the parsing yourself, which would be:

``` javascript
var sirenObj = Halpert.convert(customObj).to('siren');
```

I think the next step would be to have a function for registering formats that are not supported by this library. Something like:

``` javascript
Halpert.register('cj', cj.parser, cj,builder);
```
## Final thoughts

This really makes the halpert library a generic wrapper for parsers and builders. My thought is that if this is the way to go, the generalized format outlined above needs to be well done. Additionally, if I'm doing it this way with this generalized format, am I creating _another_ hypermedia format that just supports all of the possible hypermedia factors? 

Thoughts?

cc: @mamund

### CODE REVIEW

**Comment by mamund** [comment]
i like this idea. it will proly take some time to sort out all the generic elements needed to support a wide range of media types (HAL, Cj, Siren JSON-API,  Mason, Collection+Doc, etc.) but well worth the effort, IMO. 

in the end you may end up with a general message description model that could be incredibly useful.

**Comment by RubenVerborgh** [comment]
Great stuff! You might want to look into JSON-LD for some syntax things, including the `curies` thing which has been [implemented in `@context`](http://www.w3.org/TR/2014/REC-json-ld-20140116/#h3_compact-iris).

**Comment by smizell** [comment]
I've been reading on this stuff, and have some additional thoughts and questions.

## HTML+RDFa Elements

As I've thought through this, it's tough to get past the idea simply using HTML+RDFa as a base for everything. It almost seems like what is needed to accomplish this is a JSON representation of HTML+RDFa. Reason being, HTML+RDFa gives quite a few elements found in other media types, minus a couple.

First, it allows for describing **things** with **vocabularies** that have **links**. JSON-LD works hard at doing this, and RDFa hits on this primarily. There has even been work to convert from [RDFa to JSON-LD](http://www.w3.org/blog/2011/11/rdfa-11-meets-json-ld-in-the-d/), which looks interesting.

Also, RDFa really is a collection of things, which fits well within a lot of media types like Cj. HAL has embedded resources, and this would fit within that idea as well.

Next, HTML itself allows for meta data. Mason has a [section devoted to meta data](https://github.com/JornWildt/Mason/blob/master/Documentation/Mason-draft-1.md#meta) that resembles the `<head>` section in an HTML document. 

HTML provides actions within the responses via forms. Some media formats include actions, such as Mason and Siren, so this covers those. Even if actions are not included in the response, it is really beneficial in describing a resource in full.

HTML has support for queries, though it doesn't cover all the needs of other media types. Currently, a form with a GET method just appends the form inputs as a query string onto the action URL. Other media types like HAL and JSON API allow for URI templates, which can be used for any part of the URL, not just the query string. 

## General Hypermedia Elements

When it gets down to it, it seems like this general message description format we're thinking through here will have the following characteristics (building on my previous list).
- **Curies** - Which HTML+RDFa handles as `prefix`
- **Vocabularies** - Which HTML+RDFa calls `vocab`
- **Meta Data** - Which is in the `<head>` tag
- **Things** - Which HTML+RDFa handles as `typeof`
- **Properties** of those things - Which is `property`
- **Embedded things** - Which is used where there are `property` and `typeof` attributes in the same tag or just where one `typeof` is nested within another.
- **Links** - These links can be `<link>` tags or `<a>` tags, and can occur in the `<head>` section or anywhere in the body. These will need rel attributes and may include type attributes.
- **Actions** - Handled with `<form>` tags.
- **Queries** - Handled with `<form>` tags with GET as method.

## Limitations and Difficulties of HTML+RDFa

### Only GET and POST Support

First, HTML only currently supports GET and POST for forms. There are a couple of options here.
1. Go ahead and use other HTTP verbs, then hijack the submits and fix them. The problem here is that if you are using this HTML as the representation sent to the browser, those without Javascript will not be able to use the forms.
2. Use the `_method` input hack. This works, but I still can't decide how much I like this method (no pun intended). 

### Queries

Next, queries. As I mentioned, HTML really doesn't support URI templates, though it looks like there has been [work in the past](http://blog.whatwg.org/proposing-uri-templates-for-webforms-20) to support them. A function specific to this project could be used to support this.
1. Set a `data-template` attribute on the form that includes the URI template
2. Disable the form in the HTML in some way to keep it from being submitted until it is activated by the Javascript.
3. If disabling isn't desired, the normal behavior of the a form with GET would have to be supported along with the URI template. Meaning both `foo.com/{make}/{model}` and `foo.com/?make=Ford&model=F150` would have to be supported.

This is a very browser-specific idea, and it is also a very project-specific solution. 

### RDFa Core Initial Context

By default, HTML+RDFa supports a lot of vocabulary prefixes out of the box, which means they do not have to be specified in the document. This would require that this format support them, too, by default and then specify them where used.

## Where to Go?

HTML+RDFa seems to get you most of the way there, but I think for this all to be successful, there needs to be a JSON format that accommodates as many media types as possible. My question then is, do you simply try to make a JSON format of HTML+RDFa? Or do you come up with a way to describe these elements in JSON?

## Last Words

Once you have that generalized JSON format, you can really be off to the races. At that point, you build parses that parse _from_ formats and builders that build _to_ them. As I think through this, it seems like something similar to what jQuery does with their plugin system. You would have your core library for this, along with including only the media types you need, which would come in handy in the browser where you don't need every possible media type.

This opens things up to a lot of different directions that can be taken. Maybe this would start a revolution of HTML-First Development, where you just focus on your HTML and let these libraries handle the rest. 

## The Future's Future

Ok, so it wasn't my last words. This is a thought for way off in the distance, and way out of the scope here, but could something like this generalized format provide a means for building a web framework that is designed around hypermedia? This would mean, you build your code around resources and representations of those resources, and then even follow links within your server code instead of writing database queries. It might even require using URIs instead of foreign key ids, which makes for some interesting scalability conversation.

I think libraries like [webmachine](https://github.com/seancribbs/webmachine-ruby) are going this direction of building around resources, but they are missing this general way for describing resources.

Hope that makes sense, but just a little thinking out loud here.

**Comment by smizell** [comment]
I have now refactored the code, but it currently does not work with the [Hyperdescribe](https://github.com/smizell/hyperdescribe) format I'm working on. I'm going to go ahead and merge this in and will focus on getting that to work later.

**Pull request merged**
